FROM golang:alpine as build

WORKDIR /app
COPY . .
RUN env GOOS=linux GOARCH=amd64 go build -o k8s-ecr-login-renew .

FROM alpine:3.12.3@sha256:074d3636ebda6dd446d0d00304c4454f468237fdacf08fb0eeac90bdbfa1bac7
RUN apk --no-cache add ca-certificates
COPY --from=build /app/k8s-ecr-login-renew .
CMD ["./k8s-ecr-login-renew"]
