FROM golang:alpine as build

WORKDIR /app
COPY . .
RUN env GOOS=linux GOARCH=arm64 go build -o k8s-ecr-login-renew .

FROM alpine:3.12.3@sha256:549694ea68340c26d1d85c00039aa11ad835be279bfd475ff4284b705f92c24e
RUN apk --no-cache add ca-certificates
COPY --from=build /app/k8s-ecr-login-renew .
CMD ["./k8s-ecr-login-renew"]
